/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *label1;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *button1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label5;
  GtkWidget *label4;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  label1 = gtk_label_new (_("Welcome to MyGym"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 128, 8);
  gtk_widget_set_size_request (label1, 144, 40);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 152, 64);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 152, 112);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (entry2), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);
  gtk_entry_set_activates_default (GTK_ENTRY (entry2), TRUE);

  label2 = gtk_label_new (_("Username"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 32, 64);
  gtk_widget_set_size_request (label2, 104, 24);

  label3 = gtk_label_new (_("Password"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 40, 112);
  gtk_widget_set_size_request (label3, 80, 24);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 176, 160);
  gtk_widget_set_size_request (button1, 66, 29);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Login"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox1), label5, FALSE, FALSE, 0);

  label4 = gtk_label_new ("");
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 88, 208);
  gtk_widget_set_size_request (label4, 240, 72);

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, label3, "label3");
  GLADE_HOOKUP_OBJECT (window1, button1, "button1");
  GLADE_HOOKUP_OBJECT (window1, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1, image1, "image1");
  GLADE_HOOKUP_OBJECT (window1, label5, "label5");
  GLADE_HOOKUP_OBJECT (window1, label4, "label4");

  return window1;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed2;
  GtkWidget *label6;
  GtkWidget *notebook1;
  GtkWidget *notebook2;
  GtkWidget *empty_notebook_page;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *label20;
  GtkWidget *label7;
  GtkWidget *notebook3;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *label8;
  GtkWidget *notebook4;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *label9;
  GtkWidget *notebook5;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *label10;
  GtkWidget *notebook6;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkWidget *label32;
  GtkWidget *label11;
  GtkWidget *notebook7;
  GtkWidget *label33;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *label36;
  GtkWidget *label12;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window2), fixed2);

  label6 = gtk_label_new (_("Espace Admin"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed2), label6, 240, 0);
  gtk_widget_set_size_request (label6, 120, 40);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed2), notebook1, 16, 48);
  gtk_widget_set_size_request (notebook1, 592, 440);

  notebook2 = gtk_notebook_new ();
  gtk_widget_show (notebook2);
  gtk_container_add (GTK_CONTAINER (notebook1), notebook2);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook2), empty_notebook_page);

  label13 = gtk_label_new (_("Afficher"));
  gtk_widget_show (label13);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), label13);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook2), empty_notebook_page);

  label14 = gtk_label_new (_("Ajouter"));
  gtk_widget_show (label14);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), label14);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook2), empty_notebook_page);

  label15 = gtk_label_new (_("Modifier"));
  gtk_widget_show (label15);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 2), label15);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook2), empty_notebook_page);

  label20 = gtk_label_new (_("Supprimer"));
  gtk_widget_show (label20);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 3), label20);

  label7 = gtk_label_new (_("Admin"));
  gtk_widget_show (label7);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label7);

  notebook3 = gtk_notebook_new ();
  gtk_widget_show (notebook3);
  gtk_container_add (GTK_CONTAINER (notebook1), notebook3);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook3), empty_notebook_page);

  label16 = gtk_label_new (_("Afficher"));
  gtk_widget_show (label16);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 0), label16);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook3), empty_notebook_page);

  label17 = gtk_label_new (_("Ajouter"));
  gtk_widget_show (label17);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 1), label17);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook3), empty_notebook_page);

  label18 = gtk_label_new (_("Modifier"));
  gtk_widget_show (label18);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 2), label18);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook3), empty_notebook_page);

  label19 = gtk_label_new (_("Supprimer"));
  gtk_widget_show (label19);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 3), label19);

  label8 = gtk_label_new (_("Adherant"));
  gtk_widget_show (label8);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label8);

  notebook4 = gtk_notebook_new ();
  gtk_widget_show (notebook4);
  gtk_container_add (GTK_CONTAINER (notebook1), notebook4);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook4), empty_notebook_page);

  label21 = gtk_label_new (_("Afficher"));
  gtk_widget_show (label21);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook4), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook4), 0), label21);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook4), empty_notebook_page);

  label22 = gtk_label_new (_("Ajouter"));
  gtk_widget_show (label22);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook4), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook4), 1), label22);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook4), empty_notebook_page);

  label23 = gtk_label_new (_("Modifier"));
  gtk_widget_show (label23);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook4), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook4), 2), label23);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook4), empty_notebook_page);

  label24 = gtk_label_new (_("Supprimer"));
  gtk_widget_show (label24);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook4), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook4), 3), label24);

  label9 = gtk_label_new (_("Coach"));
  gtk_widget_show (label9);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label9);

  notebook5 = gtk_notebook_new ();
  gtk_widget_show (notebook5);
  gtk_container_add (GTK_CONTAINER (notebook1), notebook5);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook5), empty_notebook_page);

  label25 = gtk_label_new (_("Afficher"));
  gtk_widget_show (label25);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook5), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook5), 0), label25);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook5), empty_notebook_page);

  label26 = gtk_label_new (_("Ajouter"));
  gtk_widget_show (label26);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook5), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook5), 1), label26);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook5), empty_notebook_page);

  label27 = gtk_label_new (_("Modifer"));
  gtk_widget_show (label27);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook5), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook5), 2), label27);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook5), empty_notebook_page);

  label28 = gtk_label_new (_("Supprimer"));
  gtk_widget_show (label28);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook5), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook5), 3), label28);

  label10 = gtk_label_new (_("Medecin"));
  gtk_widget_show (label10);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label10);

  notebook6 = gtk_notebook_new ();
  gtk_widget_show (notebook6);
  gtk_container_add (GTK_CONTAINER (notebook1), notebook6);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook6), empty_notebook_page);

  label29 = gtk_label_new (_("Afficher"));
  gtk_widget_show (label29);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook6), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook6), 0), label29);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook6), empty_notebook_page);

  label30 = gtk_label_new (_("Ajouter"));
  gtk_widget_show (label30);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook6), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook6), 1), label30);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook6), empty_notebook_page);

  label31 = gtk_label_new (_("Modifier"));
  gtk_widget_show (label31);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook6), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook6), 2), label31);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook6), empty_notebook_page);

  label32 = gtk_label_new (_("Supprimer"));
  gtk_widget_show (label32);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook6), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook6), 3), label32);

  label11 = gtk_label_new (_("Dieticien"));
  gtk_widget_show (label11);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label11);

  notebook7 = gtk_notebook_new ();
  gtk_widget_show (notebook7);
  gtk_container_add (GTK_CONTAINER (notebook1), notebook7);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook7), empty_notebook_page);

  label33 = gtk_label_new (_("Afficher"));
  gtk_widget_show (label33);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook7), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook7), 0), label33);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook7), empty_notebook_page);

  label34 = gtk_label_new (_("Ajouter"));
  gtk_widget_show (label34);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook7), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook7), 1), label34);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook7), empty_notebook_page);

  label35 = gtk_label_new (_("Modifier"));
  gtk_widget_show (label35);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook7), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook7), 2), label35);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook7), empty_notebook_page);

  label36 = gtk_label_new (_("Supprimer"));
  gtk_widget_show (label36);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook7), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook7), 3), label36);

  label12 = gtk_label_new (_("Kinesitherapeute"));
  gtk_widget_show (label12);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 5), label12);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window2, label6, "label6");
  GLADE_HOOKUP_OBJECT (window2, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window2, notebook2, "notebook2");
  GLADE_HOOKUP_OBJECT (window2, label13, "label13");
  GLADE_HOOKUP_OBJECT (window2, label14, "label14");
  GLADE_HOOKUP_OBJECT (window2, label15, "label15");
  GLADE_HOOKUP_OBJECT (window2, label20, "label20");
  GLADE_HOOKUP_OBJECT (window2, label7, "label7");
  GLADE_HOOKUP_OBJECT (window2, notebook3, "notebook3");
  GLADE_HOOKUP_OBJECT (window2, label16, "label16");
  GLADE_HOOKUP_OBJECT (window2, label17, "label17");
  GLADE_HOOKUP_OBJECT (window2, label18, "label18");
  GLADE_HOOKUP_OBJECT (window2, label19, "label19");
  GLADE_HOOKUP_OBJECT (window2, label8, "label8");
  GLADE_HOOKUP_OBJECT (window2, notebook4, "notebook4");
  GLADE_HOOKUP_OBJECT (window2, label21, "label21");
  GLADE_HOOKUP_OBJECT (window2, label22, "label22");
  GLADE_HOOKUP_OBJECT (window2, label23, "label23");
  GLADE_HOOKUP_OBJECT (window2, label24, "label24");
  GLADE_HOOKUP_OBJECT (window2, label9, "label9");
  GLADE_HOOKUP_OBJECT (window2, notebook5, "notebook5");
  GLADE_HOOKUP_OBJECT (window2, label25, "label25");
  GLADE_HOOKUP_OBJECT (window2, label26, "label26");
  GLADE_HOOKUP_OBJECT (window2, label27, "label27");
  GLADE_HOOKUP_OBJECT (window2, label28, "label28");
  GLADE_HOOKUP_OBJECT (window2, label10, "label10");
  GLADE_HOOKUP_OBJECT (window2, notebook6, "notebook6");
  GLADE_HOOKUP_OBJECT (window2, label29, "label29");
  GLADE_HOOKUP_OBJECT (window2, label30, "label30");
  GLADE_HOOKUP_OBJECT (window2, label31, "label31");
  GLADE_HOOKUP_OBJECT (window2, label32, "label32");
  GLADE_HOOKUP_OBJECT (window2, label11, "label11");
  GLADE_HOOKUP_OBJECT (window2, notebook7, "notebook7");
  GLADE_HOOKUP_OBJECT (window2, label33, "label33");
  GLADE_HOOKUP_OBJECT (window2, label34, "label34");
  GLADE_HOOKUP_OBJECT (window2, label35, "label35");
  GLADE_HOOKUP_OBJECT (window2, label36, "label36");
  GLADE_HOOKUP_OBJECT (window2, label12, "label12");

  return window2;
}

GtkWidget*
create_window3 (void)
{
  GtkWidget *window3;
  GtkWidget *fixed3;
  GtkWidget *notebook8;
  GtkWidget *fixed4;
  GtkWidget *label41;
  GtkWidget *fixed6;
  GtkWidget *label42;
  GtkWidget *fixed5;
  GtkWidget *label44;
  GtkWidget *label43;
  GtkWidget *fixed8;
  GtkWidget *label45;

  window3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window3), _("window3"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (window3), fixed3);

  notebook8 = gtk_notebook_new ();
  gtk_widget_show (notebook8);
  gtk_fixed_put (GTK_FIXED (fixed3), notebook8, 0, 0);
  gtk_widget_set_size_request (notebook8, 544, 408);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook8), fixed4);

  label41 = gtk_label_new (_("Modifier"));
  gtk_widget_show (label41);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook8), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook8), 0), label41);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook8), fixed6);

  label42 = gtk_label_new (_("Supprimer"));
  gtk_widget_show (label42);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook8), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook8), 1), label42);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook8), fixed5);

  label44 = gtk_label_new (_("label44"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed5), label44, 56, 32);
  gtk_widget_set_size_request (label44, 49, 17);

  label43 = gtk_label_new (_("Afficher"));
  gtk_widget_show (label43);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook8), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook8), 2), label43);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (notebook8), fixed8);

  label45 = gtk_label_new (_("Ajouter"));
  gtk_widget_show (label45);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook8), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook8), 3), label45);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3, window3, "window3");
  GLADE_HOOKUP_OBJECT (window3, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window3, notebook8, "notebook8");
  GLADE_HOOKUP_OBJECT (window3, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window3, label41, "label41");
  GLADE_HOOKUP_OBJECT (window3, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window3, label42, "label42");
  GLADE_HOOKUP_OBJECT (window3, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window3, label44, "label44");
  GLADE_HOOKUP_OBJECT (window3, label43, "label43");
  GLADE_HOOKUP_OBJECT (window3, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (window3, label45, "label45");

  return window3;
}

GtkWidget*
create_window4 (void)
{
  GtkWidget *window4;
  GtkWidget *fixed7;
  GtkWidget *notebook9;
  GtkWidget *notebook10;
  GtkWidget *fixed9;
  GtkWidget *label52;
  GtkWidget *label51;
  GtkWidget *label53;
  GtkWidget *label54;
  GtkWidget *label55;
  GtkWidget *button2;
  GtkWidget *label56;
  GtkWidget *label57;
  GtkWidget *label58;
  GtkWidget *label59;
  GtkWidget *label49;
  GtkWidget *fixed10;
  GtkWidget *fixed11;
  GtkWidget *label60;
  GtkWidget *entry3;
  GtkWidget *label61;
  GtkWidget *entry4;
  GtkWidget *label62;
  GtkWidget *label63;
  GtkWidget *entry5;
  GtkWidget *button3;
  GtkWidget *label64;
  GtkWidget *label65;
  GtkWidget *label66;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *label50;
  GtkWidget *label46;
  GtkWidget *fixed12;
  GtkWidget *label67;
  GtkWidget *comboboxentry1;
  GtkWidget *label68;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkWidget *label69;
  GtkWidget *label71;
  GtkWidget *label70;
  GtkWidget *label72;
  GtkWidget *button4;
  GtkWidget *label47;
  GtkWidget *empty_notebook_page;
  GtkWidget *label48;

  window4 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window4), _("window4"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (window4), fixed7);

  notebook9 = gtk_notebook_new ();
  gtk_widget_show (notebook9);
  gtk_fixed_put (GTK_FIXED (fixed7), notebook9, 0, 0);
  gtk_widget_set_size_request (notebook9, 1296, 680);

  notebook10 = gtk_notebook_new ();
  gtk_widget_show (notebook10);
  gtk_container_add (GTK_CONTAINER (notebook9), notebook10);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (notebook10), fixed9);

  label52 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed9), label52, 16, 128);
  gtk_widget_set_size_request (label52, 136, 32);

  label51 = gtk_label_new (_("Welcome coach"));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed9), label51, 456, 8);
  gtk_widget_set_size_request (label51, 336, 104);

  label53 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed9), label53, 40, 168);
  gtk_widget_set_size_request (label53, 72, 32);

  label54 = gtk_label_new (_("Specialit\303\251e :"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed9), label54, 32, 208);
  gtk_widget_set_size_request (label54, 88, 24);

  label55 = gtk_label_new (_("Date de recrutement :"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed9), label55, 16, 232);
  gtk_widget_set_size_request (label55, 152, 56);

  button2 = gtk_button_new_with_mnemonic (_("Modifier Votre profile"));
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed9), button2, 488, 440);
  gtk_widget_set_size_request (button2, 248, 48);

  label56 = gtk_label_new (_("label56"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed9), label56, 200, 136);
  gtk_widget_set_size_request (label56, 49, 17);

  label57 = gtk_label_new (_("label57"));
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (fixed9), label57, 192, 176);
  gtk_widget_set_size_request (label57, 49, 17);

  label58 = gtk_label_new (_("label58"));
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (fixed9), label58, 192, 216);
  gtk_widget_set_size_request (label58, 49, 17);

  label59 = gtk_label_new (_("../../...."));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (fixed9), label59, 200, 248);
  gtk_widget_set_size_request (label59, 49, 17);

  label49 = gtk_label_new (_("Welcome"));
  gtk_widget_show (label49);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook10), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook10), 0), label49);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (notebook10), fixed10);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_fixed_put (GTK_FIXED (fixed10), fixed11, 952, 416);
  gtk_widget_set_size_request (fixed11, 50, 50);

  label60 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (fixed10), label60, 64, 112);
  gtk_widget_set_size_request (label60, 88, 40);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed10), entry3, 168, 112);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  label61 = gtk_label_new (_("Prenom :"));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed10), label61, 64, 184);
  gtk_widget_set_size_request (label61, 72, 24);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed10), entry4, 168, 176);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  label62 = gtk_label_new (_("Date de recrutement :"));
  gtk_widget_show (label62);
  gtk_fixed_put (GTK_FIXED (fixed10), label62, 24, 288);
  gtk_widget_set_size_request (label62, 152, 48);

  label63 = gtk_label_new (_("Specialit\303\251e :"));
  gtk_widget_show (label63);
  gtk_fixed_put (GTK_FIXED (fixed10), label63, 40, 248);
  gtk_widget_set_size_request (label63, 96, 32);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed10), entry5, 168, 248);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  button3 = gtk_button_new_with_mnemonic (_("Valider "));
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed10), button3, 496, 496);
  gtk_widget_set_size_request (button3, 152, 40);

  label64 = gtk_label_new (_("jour :"));
  gtk_widget_show (label64);
  gtk_fixed_put (GTK_FIXED (fixed10), label64, 184, 304);
  gtk_widget_set_size_request (label64, 49, 17);

  label65 = gtk_label_new (_("mois :"));
  gtk_widget_show (label65);
  gtk_fixed_put (GTK_FIXED (fixed10), label65, 344, 304);
  gtk_widget_set_size_request (label65, 49, 17);

  label66 = gtk_label_new (_("Annee :"));
  gtk_widget_show (label66);
  gtk_fixed_put (GTK_FIXED (fixed10), label66, 568, 304);
  gtk_widget_set_size_request (label66, 49, 17);

  spinbutton1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed10), spinbutton1, 240, 296);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  spinbutton2_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed10), spinbutton2, 440, 296);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  spinbutton3_adj = gtk_adjustment_new (1970, 1970, 2018, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed10), spinbutton3, 648, 296);
  gtk_widget_set_size_request (spinbutton3, 60, 27);

  label50 = gtk_label_new (_("Modification du profile"));
  gtk_widget_show (label50);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook10), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook10), 1), label50);

  label46 = gtk_label_new (_("Profile"));
  gtk_widget_show (label46);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook9), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook9), 0), label46);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (notebook9), fixed12);

  label67 = gtk_label_new (_("Cours :"));
  gtk_widget_show (label67);
  gtk_fixed_put (GTK_FIXED (fixed12), label67, 64, 128);
  gtk_widget_set_size_request (label67, 88, 40);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed12), comboboxentry1, 176, 128);
  gtk_widget_set_size_request (comboboxentry1, 189, 29);

  label68 = gtk_label_new (_("Disponibilit\303\251e :"));
  gtk_widget_show (label68);
  gtk_fixed_put (GTK_FIXED (fixed12), label68, 32, 216);
  gtk_widget_set_size_request (label68, 120, 32);

  spinbutton4_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton4, 240, 216);
  gtk_widget_set_size_request (spinbutton4, 60, 27);

  spinbutton5_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton5, 440, 216);
  gtk_widget_set_size_request (spinbutton5, 60, 27);

  spinbutton6_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton6, 616, 216);
  gtk_widget_set_size_request (spinbutton6, 60, 27);

  label69 = gtk_label_new (_("Jour"));
  gtk_widget_show (label69);
  gtk_fixed_put (GTK_FIXED (fixed12), label69, 160, 224);
  gtk_widget_set_size_request (label69, 49, 17);

  label71 = gtk_label_new (_("mois"));
  gtk_widget_show (label71);
  gtk_fixed_put (GTK_FIXED (fixed12), label71, 336, 216);
  gtk_widget_set_size_request (label71, 72, 24);

  label70 = gtk_label_new (_("Jour"));
  gtk_widget_show (label70);
  gtk_fixed_put (GTK_FIXED (fixed12), label70, 160, 224);
  gtk_widget_set_size_request (label70, 49, 17);

  label72 = gtk_label_new (_("ann\303\251e"));
  gtk_widget_show (label72);
  gtk_fixed_put (GTK_FIXED (fixed12), label72, 536, 216);
  gtk_widget_set_size_request (label72, 57, 25);

  button4 = gtk_button_new_with_mnemonic (_("Valider "));
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed12), button4, 480, 400);
  gtk_widget_set_size_request (button4, 160, 40);

  label47 = gtk_label_new (_("Evenement"));
  gtk_widget_show (label47);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook9), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook9), 1), label47);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook9), empty_notebook_page);

  label48 = gtk_label_new (_("Afficher les adherents"));
  gtk_widget_show (label48);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook9), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook9), 2), label48);

  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window4, window4, "window4");
  GLADE_HOOKUP_OBJECT (window4, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window4, notebook9, "notebook9");
  GLADE_HOOKUP_OBJECT (window4, notebook10, "notebook10");
  GLADE_HOOKUP_OBJECT (window4, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (window4, label52, "label52");
  GLADE_HOOKUP_OBJECT (window4, label51, "label51");
  GLADE_HOOKUP_OBJECT (window4, label53, "label53");
  GLADE_HOOKUP_OBJECT (window4, label54, "label54");
  GLADE_HOOKUP_OBJECT (window4, label55, "label55");
  GLADE_HOOKUP_OBJECT (window4, button2, "button2");
  GLADE_HOOKUP_OBJECT (window4, label56, "label56");
  GLADE_HOOKUP_OBJECT (window4, label57, "label57");
  GLADE_HOOKUP_OBJECT (window4, label58, "label58");
  GLADE_HOOKUP_OBJECT (window4, label59, "label59");
  GLADE_HOOKUP_OBJECT (window4, label49, "label49");
  GLADE_HOOKUP_OBJECT (window4, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (window4, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (window4, label60, "label60");
  GLADE_HOOKUP_OBJECT (window4, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (window4, label61, "label61");
  GLADE_HOOKUP_OBJECT (window4, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (window4, label62, "label62");
  GLADE_HOOKUP_OBJECT (window4, label63, "label63");
  GLADE_HOOKUP_OBJECT (window4, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (window4, button3, "button3");
  GLADE_HOOKUP_OBJECT (window4, label64, "label64");
  GLADE_HOOKUP_OBJECT (window4, label65, "label65");
  GLADE_HOOKUP_OBJECT (window4, label66, "label66");
  GLADE_HOOKUP_OBJECT (window4, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (window4, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (window4, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (window4, label50, "label50");
  GLADE_HOOKUP_OBJECT (window4, label46, "label46");
  GLADE_HOOKUP_OBJECT (window4, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (window4, label67, "label67");
  GLADE_HOOKUP_OBJECT (window4, comboboxentry1, "comboboxentry1");
  GLADE_HOOKUP_OBJECT (window4, label68, "label68");
  GLADE_HOOKUP_OBJECT (window4, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (window4, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (window4, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (window4, label69, "label69");
  GLADE_HOOKUP_OBJECT (window4, label71, "label71");
  GLADE_HOOKUP_OBJECT (window4, label70, "label70");
  GLADE_HOOKUP_OBJECT (window4, label72, "label72");
  GLADE_HOOKUP_OBJECT (window4, button4, "button4");
  GLADE_HOOKUP_OBJECT (window4, label47, "label47");
  GLADE_HOOKUP_OBJECT (window4, label48, "label48");

  return window4;
}

GtkWidget*
create_window5 (void)
{
  GtkWidget *window5;
  GtkWidget *fixed13;
  GtkWidget *notebook11;
  GtkWidget *empty_notebook_page;
  GtkWidget *label73;
  GtkWidget *fixed14;
  GtkWidget *notebook12;
  GtkWidget *fixed15;
  GtkWidget *label79;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkWidget *label80;
  GtkWidget *label81;
  GtkWidget *combobox1;
  GtkWidget *label82;
  GtkObject *spinbutton7_adj;
  GtkWidget *spinbutton7;
  GtkWidget *label83;
  GtkObject *spinbutton8_adj;
  GtkWidget *spinbutton8;
  GtkObject *spinbutton9_adj;
  GtkWidget *spinbutton9;
  GtkWidget *label84;
  GtkWidget *label85;
  GtkWidget *label75;
  GtkWidget *label76;
  GtkWidget *label77;
  GtkWidget *label78;
  GtkWidget *label74;

  window5 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window5), _("window5"));

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (window5), fixed13);

  notebook11 = gtk_notebook_new ();
  gtk_widget_show (notebook11);
  gtk_fixed_put (GTK_FIXED (fixed13), notebook11, 0, 0);
  gtk_widget_set_size_request (notebook11, 952, 648);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook11), empty_notebook_page);

  label73 = gtk_label_new (_("aceuil"));
  gtk_widget_show (label73);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook11), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook11), 0), label73);

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (notebook11), fixed14);

  notebook12 = gtk_notebook_new ();
  gtk_widget_show (notebook12);
  gtk_fixed_put (GTK_FIXED (fixed14), notebook12, 0, 0);
  gtk_widget_set_size_request (notebook12, 952, 616);

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (notebook12), fixed15);

  label79 = gtk_label_new (_("Nom"));
  gtk_widget_show (label79);
  gtk_fixed_put (GTK_FIXED (fixed15), label79, 24, 24);
  gtk_widget_set_size_request (label79, 49, 17);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed15), entry6, 112, 16);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed15), entry7, 112, 56);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  label80 = gtk_label_new (_("Pr\303\251nom"));
  gtk_widget_show (label80);
  gtk_fixed_put (GTK_FIXED (fixed15), label80, 24, 64);
  gtk_widget_set_size_request (label80, 64, 16);

  label81 = gtk_label_new (_("sexe"));
  gtk_widget_show (label81);
  gtk_fixed_put (GTK_FIXED (fixed15), label81, 32, 104);
  gtk_widget_set_size_request (label81, 49, 17);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed15), combobox1, 104, 96);
  gtk_widget_set_size_request (combobox1, 176, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Homme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Femme"));

  label82 = gtk_label_new (_("Date de naissance :"));
  gtk_widget_show (label82);
  gtk_fixed_put (GTK_FIXED (fixed15), label82, 8, 152);
  gtk_widget_set_size_request (label82, 152, 16);

  spinbutton7_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton7 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton7_adj), 1, 0);
  gtk_widget_show (spinbutton7);
  gtk_fixed_put (GTK_FIXED (fixed15), spinbutton7, 232, 144);
  gtk_widget_set_size_request (spinbutton7, 60, 27);

  label83 = gtk_label_new (_("Jour"));
  gtk_widget_show (label83);
  gtk_fixed_put (GTK_FIXED (fixed15), label83, 168, 152);
  gtk_widget_set_size_request (label83, 49, 17);

  spinbutton8_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton8 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton8_adj), 1, 0);
  gtk_widget_show (spinbutton8);
  gtk_fixed_put (GTK_FIXED (fixed15), spinbutton8, 408, 144);
  gtk_widget_set_size_request (spinbutton8, 60, 27);

  spinbutton9_adj = gtk_adjustment_new (1, 1900, 2050, 1, 10, 10);
  spinbutton9 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton9_adj), 1, 0);
  gtk_widget_show (spinbutton9);
  gtk_fixed_put (GTK_FIXED (fixed15), spinbutton9, 576, 144);
  gtk_widget_set_size_request (spinbutton9, 60, 27);

  label84 = gtk_label_new (_("Moins"));
  gtk_widget_show (label84);
  gtk_fixed_put (GTK_FIXED (fixed15), label84, 336, 152);
  gtk_widget_set_size_request (label84, 49, 17);

  label85 = gtk_label_new (_("Anne\303\251"));
  gtk_widget_show (label85);
  gtk_fixed_put (GTK_FIXED (fixed15), label85, 520, 152);
  gtk_widget_set_size_request (label85, 49, 17);

  label75 = gtk_label_new (_("Ajouter"));
  gtk_widget_show (label75);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook12), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook12), 0), label75);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook12), empty_notebook_page);

  label76 = gtk_label_new (_("Afficher"));
  gtk_widget_show (label76);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook12), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook12), 1), label76);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook12), empty_notebook_page);

  label77 = gtk_label_new (_("Modifier"));
  gtk_widget_show (label77);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook12), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook12), 2), label77);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook12), empty_notebook_page);

  label78 = gtk_label_new (_("Supprimer"));
  gtk_widget_show (label78);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook12), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook12), 3), label78);

  label74 = gtk_label_new (_("fiche m\303\251dical"));
  gtk_widget_show (label74);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook11), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook11), 1), label74);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window5, window5, "window5");
  GLADE_HOOKUP_OBJECT (window5, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (window5, notebook11, "notebook11");
  GLADE_HOOKUP_OBJECT (window5, label73, "label73");
  GLADE_HOOKUP_OBJECT (window5, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (window5, notebook12, "notebook12");
  GLADE_HOOKUP_OBJECT (window5, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (window5, label79, "label79");
  GLADE_HOOKUP_OBJECT (window5, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (window5, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (window5, label80, "label80");
  GLADE_HOOKUP_OBJECT (window5, label81, "label81");
  GLADE_HOOKUP_OBJECT (window5, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (window5, label82, "label82");
  GLADE_HOOKUP_OBJECT (window5, spinbutton7, "spinbutton7");
  GLADE_HOOKUP_OBJECT (window5, label83, "label83");
  GLADE_HOOKUP_OBJECT (window5, spinbutton8, "spinbutton8");
  GLADE_HOOKUP_OBJECT (window5, spinbutton9, "spinbutton9");
  GLADE_HOOKUP_OBJECT (window5, label84, "label84");
  GLADE_HOOKUP_OBJECT (window5, label85, "label85");
  GLADE_HOOKUP_OBJECT (window5, label75, "label75");
  GLADE_HOOKUP_OBJECT (window5, label76, "label76");
  GLADE_HOOKUP_OBJECT (window5, label77, "label77");
  GLADE_HOOKUP_OBJECT (window5, label78, "label78");
  GLADE_HOOKUP_OBJECT (window5, label74, "label74");

  return window5;
}

GtkWidget*
create_window6 (void)
{
  GtkWidget *window6;
  GtkWidget *fixed16;
  GtkWidget *notebook13;
  GtkWidget *empty_notebook_page;
  GtkWidget *label87;
  GtkWidget *label88;
  GtkWidget *label89;

  window6 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window6), _("window6"));

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (window6), fixed16);

  notebook13 = gtk_notebook_new ();
  gtk_widget_show (notebook13);
  gtk_fixed_put (GTK_FIXED (fixed16), notebook13, 8, 16);
  gtk_widget_set_size_request (notebook13, 752, 576);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook13), empty_notebook_page);

  label87 = gtk_label_new (_("Profil"));
  gtk_widget_show (label87);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook13), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook13), 0), label87);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook13), empty_notebook_page);

  label88 = gtk_label_new (_("Gestion des s\303\251ance de cures"));
  gtk_widget_show (label88);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook13), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook13), 1), label88);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook13), empty_notebook_page);

  label89 = gtk_label_new (_("Fiche m\303\251dical"));
  gtk_widget_show (label89);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook13), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook13), 2), label89);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window6, window6, "window6");
  GLADE_HOOKUP_OBJECT (window6, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (window6, notebook13, "notebook13");
  GLADE_HOOKUP_OBJECT (window6, label87, "label87");
  GLADE_HOOKUP_OBJECT (window6, label88, "label88");
  GLADE_HOOKUP_OBJECT (window6, label89, "label89");

  return window6;
}

GtkWidget*
create_window7 (void)
{
  GtkWidget *window7;
  GtkWidget *fixed17;
  GtkWidget *notebook14;
  GtkWidget *notebook15;
  GtkWidget *empty_notebook_page;
  GtkWidget *label92;
  GtkWidget *label93;
  GtkWidget *label94;
  GtkWidget *label95;
  GtkWidget *label90;
  GtkWidget *notebook16;
  GtkWidget *label96;
  GtkWidget *label97;
  GtkWidget *label91;

  window7 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window7), _("window7"));

  fixed17 = gtk_fixed_new ();
  gtk_widget_show (fixed17);
  gtk_container_add (GTK_CONTAINER (window7), fixed17);

  notebook14 = gtk_notebook_new ();
  gtk_widget_show (notebook14);
  gtk_fixed_put (GTK_FIXED (fixed17), notebook14, 0, 0);
  gtk_widget_set_size_request (notebook14, 480, 472);

  notebook15 = gtk_notebook_new ();
  gtk_widget_show (notebook15);
  gtk_container_add (GTK_CONTAINER (notebook14), notebook15);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook15), empty_notebook_page);

  label92 = gtk_label_new (_("Ajouter"));
  gtk_widget_show (label92);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook15), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook15), 0), label92);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook15), empty_notebook_page);

  label93 = gtk_label_new (_("Modifier"));
  gtk_widget_show (label93);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook15), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook15), 1), label93);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook15), empty_notebook_page);

  label94 = gtk_label_new (_("Supprimer"));
  gtk_widget_show (label94);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook15), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook15), 2), label94);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook15), empty_notebook_page);

  label95 = gtk_label_new (_("Afficher"));
  gtk_widget_show (label95);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook15), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook15), 3), label95);

  label90 = gtk_label_new (_("Profil"));
  gtk_widget_show (label90);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook14), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook14), 0), label90);

  notebook16 = gtk_notebook_new ();
  gtk_widget_show (notebook16);
  gtk_container_add (GTK_CONTAINER (notebook14), notebook16);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook16), empty_notebook_page);

  label96 = gtk_label_new (_("Afficher"));
  gtk_widget_show (label96);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook16), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook16), 0), label96);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook16), empty_notebook_page);

  label97 = gtk_label_new (_("Modifier"));
  gtk_widget_show (label97);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook16), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook16), 1), label97);

  label91 = gtk_label_new (_("Fiche Medicale"));
  gtk_widget_show (label91);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook14), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook14), 1), label91);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window7, window7, "window7");
  GLADE_HOOKUP_OBJECT (window7, fixed17, "fixed17");
  GLADE_HOOKUP_OBJECT (window7, notebook14, "notebook14");
  GLADE_HOOKUP_OBJECT (window7, notebook15, "notebook15");
  GLADE_HOOKUP_OBJECT (window7, label92, "label92");
  GLADE_HOOKUP_OBJECT (window7, label93, "label93");
  GLADE_HOOKUP_OBJECT (window7, label94, "label94");
  GLADE_HOOKUP_OBJECT (window7, label95, "label95");
  GLADE_HOOKUP_OBJECT (window7, label90, "label90");
  GLADE_HOOKUP_OBJECT (window7, notebook16, "notebook16");
  GLADE_HOOKUP_OBJECT (window7, label96, "label96");
  GLADE_HOOKUP_OBJECT (window7, label97, "label97");
  GLADE_HOOKUP_OBJECT (window7, label91, "label91");

  return window7;
}

